### PR TITLE
fix(btw): Allow injection, embracing in inputs

### LINKED ISSUE #28: passing `btw()` inputs programmatically
Ran into this while working on a tool that integrates with btw yesterday:

```r
btw::btw(paste0("{", "dplyr", "}"))
#> ```r
#> paste0("{", "dplyr", "}")
#> #> [1] "{dplyr}"
#> ```
```

I'd hoped that it would interpret the evaluated `"{dplyr}"` as the usual package shorthand. Ultimately, I [ended up using `eval_bare(call2())`](https://github.com/simonpcouch/thonk/blob/ce067de63eb17225eb109314a8d9c214f1d1948c/R/thonk.R#L64-L73) to do so.

### PR DESCRIPTION
**Pull request by gadenbuie**
Fixes #28

Small change to `enquos(...)` the `...` in `btw()` so that we can support injection and embracing. These will all work the same:

```r
btw(!!sprintf("{%s}", "tibble"))

pkg <- "{tibble}"
btw({{ pkg }})

btw("{tibble}")
```

### CODE REVIEW

File: tests/testthat/test-btw.R [hunk 1]
```diff
@@ -10,7 +10,7 @@ test_that("btw() preserves order", {
   expect_snapshot(cli::cat_line(btw(two, one)))
 })
 
-test_that("btw() with prompt stings", {
+test_that("btw() can include prompt stings", {
```
Comment (simonpcouch) [inline tests/testthat/test-btw.R:13]:
```suggestion
test_that("btw() can include prompt strings", {
```

Not due to this PR, but:

**Review by simonpcouch — APPROVED** [review]
:yay:

File: tests/testthat/test-btw.R (hunk 1 above)
Comment (gadenbuie) [reply tests/testthat/test-btw.R:13]: haha prompt stings from tiny prompt injections
